services:
  web:
    build:
      context: .
      dockerfile: ./cmd/web/Dockerfile
    depends_on:
      - redis
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - ".env"
      - "./cmd/web/.env"
    develop:
      watch:
      - action: rebuild
        path: .
  pc-agent:
    build:
      context: .
      dockerfile: ./cmd/pc-agent/Dockerfile
    depends_on:
      - redis
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    env_file: 
      - ".env"
      - "./cmd/pc-agent/.env"
    develop:
      watch:
      - action: rebuild
        path: .
  raspberry-agent:
    build:
      context: .
      dockerfile: ./cmd/raspberry-agent/Dockerfile
    depends_on:
      - redis
    env_file: 
      - ".env"
      - "./cmd/raspberry-agent/.env"
    develop:
      watch:
      - action: rebuild
        path: .
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file: 
      - ".env"
    command: >
      sh -c "echo \"user $REDIS_USER on >$REDIS_PASSWORD ~* +@all\" > /tmp/users.acl && redis-server --aclfile /tmp/users.acl"
    volumes:
      - redis-data:/data
volumes:
  redis-data: