// Code generated by MockGen. DO NOT EDIT.
// Source: wol.go
//
// Generated by this command:
//
//	mockgen -source=wol.go -destination=mock/wol.go -package=mock -mock_names=Sender=MockSender
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendMagicPacket mocks base method.
func (m *MockSender) SendMagicPacket(ctx context.Context, networkAdddress *net.UDPAddr, mac net.HardwareAddr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMagicPacket", ctx, networkAdddress, mac)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMagicPacket indicates an expected call of SendMagicPacket.
func (mr *MockSenderMockRecorder) SendMagicPacket(ctx, networkAdddress, mac any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMagicPacket", reflect.TypeOf((*MockSender)(nil).SendMagicPacket), ctx, networkAdddress, mac)
}
