// Code generated by MockGen. DO NOT EDIT.
// Source: command.go
//
// Generated by this command:
//
//	mockgen -source=command.go -destination=mock/command.go -package=mock -mock_names=CommandExecutor=MockCommandExecutor,PlatformExecutor=MockPlatformExecutor
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockCommandExecutor) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockCommandExecutorMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockCommandExecutor)(nil).Shutdown), ctx)
}

// MockPlatformExecutor is a mock of PlatformExecutor interface.
type MockPlatformExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformExecutorMockRecorder
	isgomock struct{}
}

// MockPlatformExecutorMockRecorder is the mock recorder for MockPlatformExecutor.
type MockPlatformExecutorMockRecorder struct {
	mock *MockPlatformExecutor
}

// NewMockPlatformExecutor creates a new mock instance.
func NewMockPlatformExecutor(ctrl *gomock.Controller) *MockPlatformExecutor {
	mock := &MockPlatformExecutor{ctrl: ctrl}
	mock.recorder = &MockPlatformExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatformExecutor) EXPECT() *MockPlatformExecutorMockRecorder {
	return m.recorder
}

// GetPlatformName mocks base method.
func (m *MockPlatformExecutor) GetPlatformName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPlatformName indicates an expected call of GetPlatformName.
func (mr *MockPlatformExecutorMockRecorder) GetPlatformName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformName", reflect.TypeOf((*MockPlatformExecutor)(nil).GetPlatformName))
}

// Shutdown mocks base method.
func (m *MockPlatformExecutor) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPlatformExecutorMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockPlatformExecutor)(nil).Shutdown), ctx)
}
