// Code generated by MockGen. DO NOT EDIT.
// Source: command.go
//
// Generated by this command:
//
//	mockgen -source=command.go -destination=mock/command.go -package=mock -mock_names=CommandExecutor=MockCommandExecutor
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/CedricThomas/console/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// ListGrubEntries mocks base method.
func (m *MockCommandExecutor) ListGrubEntries(ctx context.Context) ([]domain.BootEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrubEntries", ctx)
	ret0, _ := ret[0].([]domain.BootEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrubEntries indicates an expected call of ListGrubEntries.
func (mr *MockCommandExecutorMockRecorder) ListGrubEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrubEntries", reflect.TypeOf((*MockCommandExecutor)(nil).ListGrubEntries), ctx)
}

// Reboot mocks base method.
func (m *MockCommandExecutor) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockCommandExecutorMockRecorder) Reboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockCommandExecutor)(nil).Reboot), ctx)
}

// SetGrubReboot mocks base method.
func (m *MockCommandExecutor) SetGrubReboot(ctx context.Context, entryName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGrubReboot", ctx, entryName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGrubReboot indicates an expected call of SetGrubReboot.
func (mr *MockCommandExecutorMockRecorder) SetGrubReboot(ctx, entryName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGrubReboot", reflect.TypeOf((*MockCommandExecutor)(nil).SetGrubReboot), ctx, entryName)
}

// Shutdown mocks base method.
func (m *MockCommandExecutor) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockCommandExecutorMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockCommandExecutor)(nil).Shutdown), ctx)
}
