// Code generated by MockGen. DO NOT EDIT.
// Source: websocket.go
//
// Generated by this command:
//
//	mockgen -source=websocket.go -destination=mock/manager.go -package=mock -mock_names=Manager=MockManager
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	websocket "github.com/CedricThomas/console/internal/service/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockManager) Broadcast(msg []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockManagerMockRecorder) Broadcast(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockManager)(nil).Broadcast), msg)
}

// ClientCount mocks base method.
func (m *MockManager) ClientCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// ClientCount indicates an expected call of ClientCount.
func (mr *MockManagerMockRecorder) ClientCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCount", reflect.TypeOf((*MockManager)(nil).ClientCount))
}

// Register mocks base method.
func (m *MockManager) Register(client *websocket.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", client)
}

// Register indicates an expected call of Register.
func (mr *MockManagerMockRecorder) Register(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockManager)(nil).Register), client)
}

// Shutdown mocks base method.
func (m *MockManager) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockManager)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockManager) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager)(nil).Start))
}

// Unregister mocks base method.
func (m *MockManager) Unregister(client *websocket.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", client)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockManagerMockRecorder) Unregister(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockManager)(nil).Unregister), client)
}
