// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=mock/controller.go -package=mock -mock_names=Auth=MockAuth,Web=MockWeb,RaspberryAgent=MockRaspberryAgent,Register=MockRegister,PCAgent=MockPCAgent
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/CedricThomas/console/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// CheckAuth mocks base method.
func (m *MockAuth) CheckAuth(ctx context.Context, username, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuth", ctx, username, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuth indicates an expected call of CheckAuth.
func (mr *MockAuthMockRecorder) CheckAuth(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuth", reflect.TypeOf((*MockAuth)(nil).CheckAuth), ctx, username, password)
}

// CreateAccount mocks base method.
func (m *MockAuth) CreateAccount(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAuthMockRecorder) CreateAccount(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAuth)(nil).CreateAccount), ctx, username, password)
}

// DeleteAccount mocks base method.
func (m *MockAuth) DeleteAccount(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockAuthMockRecorder) DeleteAccount(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockAuth)(nil).DeleteAccount), ctx, username)
}

// GenerateToken mocks base method.
func (m *MockAuth) GenerateToken(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthMockRecorder) GenerateToken(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuth)(nil).GenerateToken), ctx, username)
}

// RevokeAllTokens mocks base method.
func (m *MockAuth) RevokeAllTokens(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllTokens", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllTokens indicates an expected call of RevokeAllTokens.
func (mr *MockAuthMockRecorder) RevokeAllTokens(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllTokens", reflect.TypeOf((*MockAuth)(nil).RevokeAllTokens), ctx, username)
}

// RevokeToken mocks base method.
func (m *MockAuth) RevokeToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockAuthMockRecorder) RevokeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockAuth)(nil).RevokeToken), ctx, token)
}

// ValidateToken mocks base method.
func (m *MockAuth) ValidateToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuth)(nil).ValidateToken), ctx, token)
}

// MockWeb is a mock of Web interface.
type MockWeb struct {
	ctrl     *gomock.Controller
	recorder *MockWebMockRecorder
	isgomock struct{}
}

// MockWebMockRecorder is the mock recorder for MockWeb.
type MockWebMockRecorder struct {
	mock *MockWeb
}

// NewMockWeb creates a new mock instance.
func NewMockWeb(ctrl *gomock.Controller) *MockWeb {
	mock := &MockWeb{ctrl: ctrl}
	mock.recorder = &MockWebMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeb) EXPECT() *MockWebMockRecorder {
	return m.recorder
}

// CheckAuth mocks base method.
func (m *MockWeb) CheckAuth(ctx context.Context, username, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuth", ctx, username, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuth indicates an expected call of CheckAuth.
func (mr *MockWebMockRecorder) CheckAuth(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuth", reflect.TypeOf((*MockWeb)(nil).CheckAuth), ctx, username, password)
}

// CreateAccount mocks base method.
func (m *MockWeb) CreateAccount(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockWebMockRecorder) CreateAccount(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockWeb)(nil).CreateAccount), ctx, username, password)
}

// DeleteAccount mocks base method.
func (m *MockWeb) DeleteAccount(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockWebMockRecorder) DeleteAccount(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockWeb)(nil).DeleteAccount), ctx, username)
}

// GenerateToken mocks base method.
func (m *MockWeb) GenerateToken(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockWebMockRecorder) GenerateToken(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockWeb)(nil).GenerateToken), ctx, username)
}

// ProcessMetrics mocks base method.
func (m *MockWeb) ProcessMetrics(ctx context.Context, metrics domain.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMetrics", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessMetrics indicates an expected call of ProcessMetrics.
func (mr *MockWebMockRecorder) ProcessMetrics(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMetrics", reflect.TypeOf((*MockWeb)(nil).ProcessMetrics), ctx, metrics)
}

// RevokeAllTokens mocks base method.
func (m *MockWeb) RevokeAllTokens(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllTokens", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllTokens indicates an expected call of RevokeAllTokens.
func (mr *MockWebMockRecorder) RevokeAllTokens(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllTokens", reflect.TypeOf((*MockWeb)(nil).RevokeAllTokens), ctx, username)
}

// RevokeToken mocks base method.
func (m *MockWeb) RevokeToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockWebMockRecorder) RevokeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockWeb)(nil).RevokeToken), ctx, token)
}

// SendAsyncBootCommand mocks base method.
func (m *MockWeb) SendAsyncBootCommand(ctx context.Context, osName domain.OSName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAsyncBootCommand", ctx, osName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAsyncBootCommand indicates an expected call of SendAsyncBootCommand.
func (mr *MockWebMockRecorder) SendAsyncBootCommand(ctx, osName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAsyncBootCommand", reflect.TypeOf((*MockWeb)(nil).SendAsyncBootCommand), ctx, osName)
}

// SendAsyncShutdownCommand mocks base method.
func (m *MockWeb) SendAsyncShutdownCommand(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAsyncShutdownCommand", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAsyncShutdownCommand indicates an expected call of SendAsyncShutdownCommand.
func (mr *MockWebMockRecorder) SendAsyncShutdownCommand(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAsyncShutdownCommand", reflect.TypeOf((*MockWeb)(nil).SendAsyncShutdownCommand), ctx)
}

// ValidateToken mocks base method.
func (m *MockWeb) ValidateToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockWebMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockWeb)(nil).ValidateToken), ctx, token)
}

// MockRaspberryAgent is a mock of RaspberryAgent interface.
type MockRaspberryAgent struct {
	ctrl     *gomock.Controller
	recorder *MockRaspberryAgentMockRecorder
	isgomock struct{}
}

// MockRaspberryAgentMockRecorder is the mock recorder for MockRaspberryAgent.
type MockRaspberryAgentMockRecorder struct {
	mock *MockRaspberryAgent
}

// NewMockRaspberryAgent creates a new mock instance.
func NewMockRaspberryAgent(ctrl *gomock.Controller) *MockRaspberryAgent {
	mock := &MockRaspberryAgent{ctrl: ctrl}
	mock.recorder = &MockRaspberryAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaspberryAgent) EXPECT() *MockRaspberryAgentMockRecorder {
	return m.recorder
}

// WakeUpPCAgent mocks base method.
func (m *MockRaspberryAgent) WakeUpPCAgent(ctx context.Context, osName domain.OSName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WakeUpPCAgent", ctx, osName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WakeUpPCAgent indicates an expected call of WakeUpPCAgent.
func (mr *MockRaspberryAgentMockRecorder) WakeUpPCAgent(ctx, osName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WakeUpPCAgent", reflect.TypeOf((*MockRaspberryAgent)(nil).WakeUpPCAgent), ctx, osName)
}

// MockRegister is a mock of Register interface.
type MockRegister struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterMockRecorder
	isgomock struct{}
}

// MockRegisterMockRecorder is the mock recorder for MockRegister.
type MockRegisterMockRecorder struct {
	mock *MockRegister
}

// NewMockRegister creates a new mock instance.
func NewMockRegister(ctrl *gomock.Controller) *MockRegister {
	mock := &MockRegister{ctrl: ctrl}
	mock.recorder = &MockRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegister) EXPECT() *MockRegisterMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockRegister) CreateAccount(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockRegisterMockRecorder) CreateAccount(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockRegister)(nil).CreateAccount), ctx, username, password)
}

// MockPCAgent is a mock of PCAgent interface.
type MockPCAgent struct {
	ctrl     *gomock.Controller
	recorder *MockPCAgentMockRecorder
	isgomock struct{}
}

// MockPCAgentMockRecorder is the mock recorder for MockPCAgent.
type MockPCAgentMockRecorder struct {
	mock *MockPCAgent
}

// NewMockPCAgent creates a new mock instance.
func NewMockPCAgent(ctrl *gomock.Controller) *MockPCAgent {
	mock := &MockPCAgent{ctrl: ctrl}
	mock.recorder = &MockPCAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPCAgent) EXPECT() *MockPCAgentMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockPCAgent) CreateAccount(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockPCAgentMockRecorder) CreateAccount(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockPCAgent)(nil).CreateAccount), ctx, username, password)
}

// SendCurrentHostAsyncMetrics mocks base method.
func (m *MockPCAgent) SendCurrentHostAsyncMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCurrentHostAsyncMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCurrentHostAsyncMetrics indicates an expected call of SendCurrentHostAsyncMetrics.
func (mr *MockPCAgentMockRecorder) SendCurrentHostAsyncMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCurrentHostAsyncMetrics", reflect.TypeOf((*MockPCAgent)(nil).SendCurrentHostAsyncMetrics), ctx)
}

// ShutdownCurrentHost mocks base method.
func (m *MockPCAgent) ShutdownCurrentHost(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShutdownCurrentHost", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShutdownCurrentHost indicates an expected call of ShutdownCurrentHost.
func (mr *MockPCAgentMockRecorder) ShutdownCurrentHost(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownCurrentHost", reflect.TypeOf((*MockPCAgent)(nil).ShutdownCurrentHost), ctx)
}
