// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mock/metrics.go -package=mock -mock_names=Metrics=MockMetrics
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/CedricThomas/console/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// GetLastMetrics mocks base method.
func (m *MockMetrics) GetLastMetrics(ctx context.Context) (*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMetrics", ctx)
	ret0, _ := ret[0].(*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMetrics indicates an expected call of GetLastMetrics.
func (mr *MockMetricsMockRecorder) GetLastMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMetrics", reflect.TypeOf((*MockMetrics)(nil).GetLastMetrics), ctx)
}

// ProcessMetrics mocks base method.
func (m *MockMetrics) ProcessMetrics(ctx context.Context, metrics domain.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMetrics", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessMetrics indicates an expected call of ProcessMetrics.
func (mr *MockMetricsMockRecorder) ProcessMetrics(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMetrics", reflect.TypeOf((*MockMetrics)(nil).ProcessMetrics), ctx, metrics)
}
