// Code generated by MockGen. DO NOT EDIT.
// Source: boot.go
//
// Generated by this command:
//
//	mockgen -source=boot.go -destination=mock/boot.go -package=mock -mock_names=Boot=MockBoot
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/CedricThomas/console/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBoot is a mock of Boot interface.
type MockBoot struct {
	ctrl     *gomock.Controller
	recorder *MockBootMockRecorder
	isgomock struct{}
}

// MockBootMockRecorder is the mock recorder for MockBoot.
type MockBootMockRecorder struct {
	mock *MockBoot
}

// NewMockBoot creates a new mock instance.
func NewMockBoot(ctrl *gomock.Controller) *MockBoot {
	mock := &MockBoot{ctrl: ctrl}
	mock.recorder = &MockBootMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoot) EXPECT() *MockBootMockRecorder {
	return m.recorder
}

// GetBootOS mocks base method.
func (m *MockBoot) GetBootOS(ctx context.Context) (domain.OSName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBootOS", ctx)
	ret0, _ := ret[0].(domain.OSName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBootOS indicates an expected call of GetBootOS.
func (mr *MockBootMockRecorder) GetBootOS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBootOS", reflect.TypeOf((*MockBoot)(nil).GetBootOS), ctx)
}

// ListGrubEntries mocks base method.
func (m *MockBoot) ListGrubEntries(ctx context.Context) ([]domain.BootEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrubEntries", ctx)
	ret0, _ := ret[0].([]domain.BootEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrubEntries indicates an expected call of ListGrubEntries.
func (mr *MockBootMockRecorder) ListGrubEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrubEntries", reflect.TypeOf((*MockBoot)(nil).ListGrubEntries), ctx)
}

// RebootToOS mocks base method.
func (m *MockBoot) RebootToOS(ctx context.Context, osName domain.OSName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootToOS", ctx, osName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootToOS indicates an expected call of RebootToOS.
func (mr *MockBootMockRecorder) RebootToOS(ctx, osName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootToOS", reflect.TypeOf((*MockBoot)(nil).RebootToOS), ctx, osName)
}

// StoreBootOS mocks base method.
func (m *MockBoot) StoreBootOS(ctx context.Context, osName domain.OSName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBootOS", ctx, osName)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBootOS indicates an expected call of StoreBootOS.
func (mr *MockBootMockRecorder) StoreBootOS(ctx, osName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBootOS", reflect.TypeOf((*MockBoot)(nil).StoreBootOS), ctx, osName)
}
